FluffyLabs/pvm-debugger

src/App.tsx
src/components/InitialLoadProgramCTA/index.tsx
src/components/Instructions/index.tsx
src/components/KnowledgeBase/Mobile.tsx
src/components/KnowledgeBase/index.tsx
src/components/ProgramLoader/index.tsx
src/components/ProgramUpload/Examples.tsx
src/components/ProgramUpload/FileUpload.tsx
src/components/ProgramUpload/index.tsx
src/components/PvmSelect/index.tsx
src/components/Registers/index.tsx

Closes #79
Closes #71 
Closes #74

Fix resetting the initial state & some other stuff.

---

src/App.tsx
src/components/Instructions/index.tsx
src/components/ProgramUpload/Examples.tsx
src/components/Registers/index.tsx
src/packages/pvm/pvm/disassemblify.ts
src/packages/web-worker/pvm.ts

Display correct program termination

---

src/App.tsx
src/components/MemoryPreview/PageMemory.tsx
src/components/MemoryPreview/index.tsx
src/store/workers/workersSlice.ts

This PR fixes:
https://github.com/FluffyLabs/pvm-debugger/issues/117
https://github.com/FluffyLabs/pvm-debugger/issues/112
Plus it fixes memory change on Step and Run

Fix memory reset

---

src/App.tsx
src/components/PvmSelect/index.tsx
src/components/Registers/index.tsx
src/components/ui/multi-select.tsx
tests/run-program.spec.ts

Fixes:
- #127 
- #128 (without case no 3)

PVM select refactor

---

package-lock.json
src/hooks/useDebuggerActions.ts

Clear state properly when loading new program

---

src/components/Instructions/InstructionItem.tsx
src/components/Instructions/index.tsx
src/lib/utils.ts

Highlight multiple intructions (for each PVM)

---

src/components/ProgramLoader/Assembly.tsx
src/components/ProgramLoader/Loader.tsx
src/components/ui/tabs.tsx

Fix assembly overflow in dialog

---

src/components/KnowledgeBase/index.tsx
src/utils/instructionsKnowledgeBase.ts

Fixes outstanding point in #15

Add links to graypaper reader

---

src/App.tsx

Fix max height of assembly box

---

package-lock.json
package.json
src/components/MemoryPreview/PageMemory.tsx
src/components/MemoryPreview/index.tsx
src/components/ui/input.tsx

Reverts FluffyLabs/pvm-debugger#184

Revert "Fix memory page errors"

---

src/components/ProgramLoader/Loader.tsx

Exit edit mode on new load

---

src/App.tsx

Fix current instruction preview in knowledgebase

---

src/components/Registers/index.tsx
src/hooks/useDebuggerActions.ts
src/index.d.ts
src/packages/web-worker/command-handlers/step.ts
src/packages/web-worker/pvm.ts
src/packages/web-worker/types.ts
src/store/workers/workersSlice.ts
src/types/pvm.ts

Show differences in status

---

package-lock.json
package.json
src/components/MemoryPreview/PageMemory.tsx
src/components/MemoryPreview/RangeMemory.tsx
src/components/MemoryPreview/index.tsx
src/components/ui/input.tsx

@krystian50  Please fix build and re-merge

Fix memory page errors

---

src/App.tsx
src/components/DebuggerControlls/index.tsx
src/components/ErrorWarningTooltip/index.tsx
src/components/MemoryPreview/PageMemory.tsx
src/components/ProgramLoader/Loader.tsx
src/components/ProgramLoader/index.tsx
src/components/PvmSelect/index.tsx
src/components/ui/multi-select.tsx
src/hooks/useDebuggerActions.ts
src/packages/web-worker/command-handlers/step.ts
src/store/utils.ts
src/store/workers/workersSlice.ts

Fixes https://github.com/FluffyLabs/pvm-debugger/issues/159

Fix showing worker init errors

---

src/components/DebuggerControlls/index.tsx
src/store/workers/workersSlice.ts

Add stop on demand

---

src/components/MemoryPreview/index.tsx

This PR fixes width change when longer address appears in the viewport.
Initial changes in branch https://github.com/FluffyLabs/pvm-debugger/pull/209
https://www.loom.com/share/0b38d4927f124668afa641ae2024b4ac?sid=f281cafc-e997-43f1-9fd9-9277a20051c3

Fix memory address too long

---

src/components/MemoryPreview/index.tsx
src/hooks/useDebuggerActions.ts

Refresh IsRunMode to keep proper controls on program restart

Refresh runMode on start program

---

src/store/workers/workersSlice.ts

Fix run button state when stopping on breakpoint

---

src/store/workers/workersSlice.ts

Fix comparing states with different statuses

---

src/components/DebuggerControlls/index.tsx
src/store/workers/workersSlice.ts

Refresh memory on each step

---

src/components/DebuggerControlls/index.tsx

Fix program loading via url (step not working)

---

src/components/DebuggerSettings/Content.tsx
src/components/HostCalls/HostCallsContent.tsx
src/components/HostCalls/trie-input/index.tsx
src/components/WithHelp/WithHelp.tsx
src/globals.css
src/pages/ProgramLoader.tsx

Storage tooltips
